#!/bin/bash
#PBS -N fastq_retreival
#PBS -l walltime=08:00:00
#PBS -l select=1:ncpus=4:mem=8gb


#change work directory to submission directory
cd $PBS_O_WORKDIR

#activate conda environment
eval "$(~/miniforge3/bin/conda shell.bash hook)"
conda activate hpcdemo

# output directories
sra_dir="$EPHEMERAL/NCBI/sra"
mkdir -p $sra_dir

fastq_dir="$EPHEMERAL/NCBI/fastq"
mkdir -p $fastq_dir


#SRR file
srr=SRR27482193



######################## CODE TO RETRIEVE SRA AND FASTQ FILES ###########################

# first use prefetch to retrieve the SRA files
prefetch $srr -O $sra_dir

# second use fasterq-dump to retreive the fastq file based on the .sra file
fasterq-dump "${sra_dir}/${srr}" --outdir $fastq_dir

########################################################################################


# deactivate conda environment
conda deactivate
